[2024-04-15T08:05:01.353+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: KingFX1_ETL.Extract_Response scheduled__2024-04-14T00:00:00+00:00 [queued]>
[2024-04-15T08:05:01.366+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: KingFX1_ETL.Extract_Response scheduled__2024-04-14T00:00:00+00:00 [queued]>
[2024-04-15T08:05:01.366+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 0
[2024-04-15T08:05:01.384+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): Extract_Response> on 2024-04-14 00:00:00+00:00
[2024-04-15T08:05:01.394+0000] {standard_task_runner.py:60} INFO - Started process 9314 to run task
[2024-04-15T08:05:01.399+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'KingFX1_ETL', 'Extract_Response', 'scheduled__2024-04-14T00:00:00+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/include/fx_dag.py', '--cfg-path', '/tmp/tmpjuyk62uv']
[2024-04-15T08:05:01.403+0000] {standard_task_runner.py:88} INFO - Job 98: Subtask Extract_Response
[2024-04-15T08:05:01.466+0000] {task_command.py:423} INFO - Running <TaskInstance: KingFX1_ETL.Extract_Response scheduled__2024-04-14T00:00:00+00:00 [running]> on host 65f2ce3f86e2
[2024-04-15T08:05:01.587+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='kresthill' AIRFLOW_CTX_DAG_ID='KingFX1_ETL' AIRFLOW_CTX_TASK_ID='Extract_Response' AIRFLOW_CTX_EXECUTION_DATE='2024-04-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-14T00:00:00+00:00'
[2024-04-15T08:05:01.588+0000] {logging_mixin.py:188} INFO - datascope1000723960447 tfa78vt86qrdcgqfs5m9asp2b4
[2024-04-15T08:05:01.616+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connection.py", line 616, in connect
    self.sock = sock = self._new_conn()
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connection.py", line 205, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x7f4e75266b50>: Failed to resolve 'xecdapi.xe.com' ([Errno -2] Name or service not known)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='xecdapi.xe.com', port=443): Max retries exceeded with url: /v1/convert_from.json?from=USD&to=NGN,GHS,KES,UGX,MAD,XOF,EGP (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f4e75266b50>: Failed to resolve 'xecdapi.xe.com' ([Errno -2] Name or service not known)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/include/extract.py", line 15, in extract_data
    response = requests.get(url, auth=(api_id, api_key)).json()
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='xecdapi.xe.com', port=443): Max retries exceeded with url: /v1/convert_from.json?from=USD&to=NGN,GHS,KES,UGX,MAD,XOF,EGP (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f4e75266b50>: Failed to resolve 'xecdapi.xe.com' ([Errno -2] Name or service not known)"))
[2024-04-15T08:05:01.637+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=KingFX1_ETL, task_id=Extract_Response, execution_date=20240414T000000, start_date=20240415T080501, end_date=20240415T080501
[2024-04-15T08:05:01.656+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 98 for task Extract_Response (HTTPSConnectionPool(host='xecdapi.xe.com', port=443): Max retries exceeded with url: /v1/convert_from.json?from=USD&to=NGN,GHS,KES,UGX,MAD,XOF,EGP (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f4e75266b50>: Failed to resolve 'xecdapi.xe.com' ([Errno -2] Name or service not known)")); 9314)
[2024-04-15T08:05:01.692+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-15T22:41:28.337+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: KingFX1_ETL.Extract_Response scheduled__2024-04-14T00:00:00+00:00 [queued]>
[2024-04-15T22:41:28.346+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: KingFX1_ETL.Extract_Response scheduled__2024-04-14T00:00:00+00:00 [queued]>
[2024-04-15T22:41:28.346+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 0
[2024-04-15T22:41:28.360+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): Extract_Response> on 2024-04-14 00:00:00+00:00
[2024-04-15T22:41:28.366+0000] {standard_task_runner.py:60} INFO - Started process 16809 to run task
[2024-04-15T22:41:28.369+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'KingFX1_ETL', 'Extract_Response', 'scheduled__2024-04-14T00:00:00+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/include/fx_dag.py', '--cfg-path', '/tmp/tmpuazrwqky']
[2024-04-15T22:41:28.373+0000] {standard_task_runner.py:88} INFO - Job 100: Subtask Extract_Response
[2024-04-15T22:41:28.425+0000] {task_command.py:423} INFO - Running <TaskInstance: KingFX1_ETL.Extract_Response scheduled__2024-04-14T00:00:00+00:00 [running]> on host 65f2ce3f86e2
[2024-04-15T22:41:28.507+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='kresthill' AIRFLOW_CTX_DAG_ID='KingFX1_ETL' AIRFLOW_CTX_TASK_ID='Extract_Response' AIRFLOW_CTX_EXECUTION_DATE='2024-04-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-14T00:00:00+00:00'
[2024-04-15T22:41:28.509+0000] {logging_mixin.py:188} INFO - datascope1000723960447 tfa78vt86qrdcgqfs5m9asp2b4
[2024-04-15T22:41:29.779+0000] {logging_mixin.py:188} INFO - {'terms': 'https://www.xe.com/legal/', 'privacy': 'http://www.xe.com/privacy.php', 'from': 'USD', 'amount': 1.0, 'timestamp': '2024-04-15T00:00:00Z', 'to': [{'quotecurrency': 'EGP', 'mid': 47.5475235609}, {'quotecurrency': 'GHS', 'mid': 13.4052863442}, {'quotecurrency': 'KES', 'mid': 129.9178476573}, {'quotecurrency': 'MAD', 'mid': 10.0217613841}, {'quotecurrency': 'NGN', 'mid': 1239.969221375}, {'quotecurrency': 'UGX', 'mid': 3805.5015679682}, {'quotecurrency': 'XOF', 'mid': 616.082413824}]}
[2024-04-15T22:41:29.783+0000] {logging_mixin.py:188} INFO - successfully extracted data
[2024-04-15T22:41:29.785+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-04-15T22:41:29.798+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=KingFX1_ETL, task_id=Extract_Response, execution_date=20240414T000000, start_date=20240415T224128, end_date=20240415T224129
[2024-04-15T22:41:29.833+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-15T22:41:29.845+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/models/baseoperator.py:1201: AirflowProviderDeprecationWarning: Call to deprecated class SnowflakeOperator. (This class is deprecated. Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`. Also, you can provide `hook_params={'warehouse': <warehouse>, 'database': <database>, 'role': <role>, 'schema': <schema>, 'authenticator': <authenticator>,'session_parameters': <session_parameters>}`.)
  result = cls.__new__(cls)

[2024-04-15T22:41:29.864+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-15T22:48:34.235+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: KingFX1_ETL.Extract_Response scheduled__2024-04-14T00:00:00+00:00 [queued]>
[2024-04-15T22:48:34.244+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: KingFX1_ETL.Extract_Response scheduled__2024-04-14T00:00:00+00:00 [queued]>
[2024-04-15T22:48:34.245+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 0
[2024-04-15T22:48:34.260+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): Extract_Response> on 2024-04-14 00:00:00+00:00
[2024-04-15T22:48:34.264+0000] {standard_task_runner.py:60} INFO - Started process 16941 to run task
[2024-04-15T22:48:34.267+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'KingFX1_ETL', 'Extract_Response', 'scheduled__2024-04-14T00:00:00+00:00', '--job-id', '110', '--raw', '--subdir', 'DAGS_FOLDER/include/fx_dag.py', '--cfg-path', '/tmp/tmphaj1zgwi']
[2024-04-15T22:48:34.270+0000] {standard_task_runner.py:88} INFO - Job 110: Subtask Extract_Response
[2024-04-15T22:48:34.319+0000] {task_command.py:423} INFO - Running <TaskInstance: KingFX1_ETL.Extract_Response scheduled__2024-04-14T00:00:00+00:00 [running]> on host 65f2ce3f86e2
[2024-04-15T22:48:34.397+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='kresthill' AIRFLOW_CTX_DAG_ID='KingFX1_ETL' AIRFLOW_CTX_TASK_ID='Extract_Response' AIRFLOW_CTX_EXECUTION_DATE='2024-04-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-14T00:00:00+00:00'
[2024-04-15T22:48:34.399+0000] {logging_mixin.py:188} INFO - datascope1000723960447 tfa78vt86qrdcgqfs5m9asp2b4
[2024-04-15T22:48:35.451+0000] {logging_mixin.py:188} INFO - {'terms': 'https://www.xe.com/legal/', 'privacy': 'http://www.xe.com/privacy.php', 'from': 'USD', 'amount': 1.0, 'timestamp': '2024-04-15T00:00:00Z', 'to': [{'quotecurrency': 'EGP', 'mid': 47.5475235609}, {'quotecurrency': 'GHS', 'mid': 13.4052863442}, {'quotecurrency': 'KES', 'mid': 129.9178476573}, {'quotecurrency': 'MAD', 'mid': 10.0217613841}, {'quotecurrency': 'NGN', 'mid': 1239.969221375}, {'quotecurrency': 'UGX', 'mid': 3805.5015679682}, {'quotecurrency': 'XOF', 'mid': 616.082413824}]}
[2024-04-15T22:48:35.452+0000] {logging_mixin.py:188} INFO - successfully extracted data
[2024-04-15T22:48:35.453+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-04-15T22:48:35.461+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=KingFX1_ETL, task_id=Extract_Response, execution_date=20240414T000000, start_date=20240415T224834, end_date=20240415T224835
[2024-04-15T22:48:35.528+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-15T22:48:35.546+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/models/baseoperator.py:1201: AirflowProviderDeprecationWarning: Call to deprecated class SnowflakeOperator. (This class is deprecated. Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`. Also, you can provide `hook_params={'warehouse': <warehouse>, 'database': <database>, 'role': <role>, 'schema': <schema>, 'authenticator': <authenticator>,'session_parameters': <session_parameters>}`.)
  result = cls.__new__(cls)

[2024-04-15T22:48:35.572+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-15T23:12:08.791+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: KingFX1_ETL.Extract_Response scheduled__2024-04-14T00:00:00+00:00 [queued]>
[2024-04-15T23:12:08.803+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: KingFX1_ETL.Extract_Response scheduled__2024-04-14T00:00:00+00:00 [queued]>
[2024-04-15T23:12:08.804+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 0
[2024-04-15T23:12:08.822+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): Extract_Response> on 2024-04-14 00:00:00+00:00
[2024-04-15T23:12:08.827+0000] {standard_task_runner.py:60} INFO - Started process 17311 to run task
[2024-04-15T23:12:08.832+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'KingFX1_ETL', 'Extract_Response', 'scheduled__2024-04-14T00:00:00+00:00', '--job-id', '116', '--raw', '--subdir', 'DAGS_FOLDER/include/fx_dag.py', '--cfg-path', '/tmp/tmp56uh4qrb']
[2024-04-15T23:12:08.835+0000] {standard_task_runner.py:88} INFO - Job 116: Subtask Extract_Response
[2024-04-15T23:12:09.148+0000] {task_command.py:423} INFO - Running <TaskInstance: KingFX1_ETL.Extract_Response scheduled__2024-04-14T00:00:00+00:00 [running]> on host 65f2ce3f86e2
[2024-04-15T23:12:09.296+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='kresthill' AIRFLOW_CTX_DAG_ID='KingFX1_ETL' AIRFLOW_CTX_TASK_ID='Extract_Response' AIRFLOW_CTX_EXECUTION_DATE='2024-04-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-14T00:00:00+00:00'
[2024-04-15T23:12:09.302+0000] {logging_mixin.py:188} INFO - datascope1000723960447 tfa78vt86qrdcgqfs5m9asp2b4
[2024-04-15T23:12:10.653+0000] {logging_mixin.py:188} INFO - {'terms': 'https://www.xe.com/legal/', 'privacy': 'http://www.xe.com/privacy.php', 'from': 'USD', 'amount': 1.0, 'timestamp': '2024-04-15T00:00:00Z', 'to': [{'quotecurrency': 'EGP', 'mid': 47.5475235609}, {'quotecurrency': 'GHS', 'mid': 13.4052863442}, {'quotecurrency': 'KES', 'mid': 129.9178476573}, {'quotecurrency': 'MAD', 'mid': 10.0217613841}, {'quotecurrency': 'NGN', 'mid': 1239.969221375}, {'quotecurrency': 'UGX', 'mid': 3805.5015679682}, {'quotecurrency': 'XOF', 'mid': 616.082413824}]}
[2024-04-15T23:12:10.657+0000] {logging_mixin.py:188} INFO - successfully extracted data
[2024-04-15T23:12:10.659+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-04-15T23:12:10.677+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=KingFX1_ETL, task_id=Extract_Response, execution_date=20240414T000000, start_date=20240415T231208, end_date=20240415T231210
[2024-04-15T23:12:10.737+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-15T23:12:10.774+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/models/baseoperator.py:1201: AirflowProviderDeprecationWarning: Call to deprecated class SnowflakeOperator. (This class is deprecated. Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`. Also, you can provide `hook_params={'warehouse': <warehouse>, 'database': <database>, 'role': <role>, 'schema': <schema>, 'authenticator': <authenticator>,'session_parameters': <session_parameters>}`.)
  result = cls.__new__(cls)

[2024-04-15T23:12:10.805+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
