[2024-04-12T22:02:07.114+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: KingFX_ETL.Transform_response manual__2024-04-12T22:02:01.820155+00:00 [queued]>
[2024-04-12T22:02:07.124+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: KingFX_ETL.Transform_response manual__2024-04-12T22:02:01.820155+00:00 [queued]>
[2024-04-12T22:02:07.124+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-12T22:02:07.138+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): Transform_response> on 2024-04-12 22:02:01.820155+00:00
[2024-04-12T22:02:07.142+0000] {standard_task_runner.py:60} INFO - Started process 2269 to run task
[2024-04-12T22:02:07.145+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'KingFX_ETL', 'Transform_response', 'manual__2024-04-12T22:02:01.820155+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/include/fx_dag.py', '--cfg-path', '/tmp/tmp6siht_y6']
[2024-04-12T22:02:07.148+0000] {standard_task_runner.py:88} INFO - Job 62: Subtask Transform_response
[2024-04-12T22:02:07.193+0000] {task_command.py:423} INFO - Running <TaskInstance: KingFX_ETL.Transform_response manual__2024-04-12T22:02:01.820155+00:00 [running]> on host 65f2ce3f86e2
[2024-04-12T22:02:07.264+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='KingFX_ETL' AIRFLOW_CTX_TASK_ID='Transform_response' AIRFLOW_CTX_EXECUTION_DATE='2024-04-12T22:02:01.820155+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-12T22:02:01.820155+00:00'
[2024-04-12T22:02:07.266+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/include/transform.py", line 13, in transform_data
    timestamp = response['timestamp']
KeyError: 'timestamp'
[2024-04-12T22:02:07.276+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=KingFX_ETL, task_id=Transform_response, execution_date=20240412T220201, start_date=20240412T220207, end_date=20240412T220207
[2024-04-12T22:02:07.288+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 62 for task Transform_response ('timestamp'; 2269)
[2024-04-12T22:02:07.318+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
