[2024-04-12T21:36:16.749+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: KingFX_ETL.Transform_response manual__2024-04-12T21:36:09.796259+00:00 [queued]>
[2024-04-12T21:36:16.758+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: KingFX_ETL.Transform_response manual__2024-04-12T21:36:09.796259+00:00 [queued]>
[2024-04-12T21:36:16.759+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-12T21:36:16.776+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): Transform_response> on 2024-04-12 21:36:09.796259+00:00
[2024-04-12T21:36:16.781+0000] {standard_task_runner.py:60} INFO - Started process 1848 to run task
[2024-04-12T21:36:16.784+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'KingFX_ETL', 'Transform_response', 'manual__2024-04-12T21:36:09.796259+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/include/fx_dag.py', '--cfg-path', '/tmp/tmph_bzebjb']
[2024-04-12T21:36:16.786+0000] {standard_task_runner.py:88} INFO - Job 50: Subtask Transform_response
[2024-04-12T21:36:16.831+0000] {task_command.py:423} INFO - Running <TaskInstance: KingFX_ETL.Transform_response manual__2024-04-12T21:36:09.796259+00:00 [running]> on host 65f2ce3f86e2
[2024-04-12T21:36:16.899+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='KingFX_ETL' AIRFLOW_CTX_TASK_ID='Transform_response' AIRFLOW_CTX_EXECUTION_DATE='2024-04-12T21:36:09.796259+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-12T21:36:09.796259+00:00'
[2024-04-12T21:36:16.901+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/include/transform.py", line 13, in transform_data
    timestamp = response['timestamp']
KeyError: 'timestamp'
[2024-04-12T21:36:16.913+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=KingFX_ETL, task_id=Transform_response, execution_date=20240412T213609, start_date=20240412T213616, end_date=20240412T213616
[2024-04-12T21:36:16.925+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 50 for task Transform_response ('timestamp'; 1848)
[2024-04-12T21:36:16.957+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
