[2024-04-12T22:52:01.368+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: KingFX1_ETL.Transform_response scheduled__2024-04-11T00:00:00+00:00 [queued]>
[2024-04-12T22:52:01.378+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: KingFX1_ETL.Transform_response scheduled__2024-04-11T00:00:00+00:00 [queued]>
[2024-04-12T22:52:01.379+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-12T22:52:01.392+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): Transform_response> on 2024-04-11 00:00:00+00:00
[2024-04-12T22:52:01.396+0000] {standard_task_runner.py:60} INFO - Started process 3060 to run task
[2024-04-12T22:52:01.399+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'KingFX1_ETL', 'Transform_response', 'scheduled__2024-04-11T00:00:00+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/include/fx_dag.py', '--cfg-path', '/tmp/tmp1pj_hcun']
[2024-04-12T22:52:01.402+0000] {standard_task_runner.py:88} INFO - Job 74: Subtask Transform_response
[2024-04-12T22:52:01.452+0000] {task_command.py:423} INFO - Running <TaskInstance: KingFX1_ETL.Transform_response scheduled__2024-04-11T00:00:00+00:00 [running]> on host 65f2ce3f86e2
[2024-04-12T22:52:01.523+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='KingFX1_ETL' AIRFLOW_CTX_TASK_ID='Transform_response' AIRFLOW_CTX_EXECUTION_DATE='2024-04-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-11T00:00:00+00:00'
[2024-04-12T22:52:01.525+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/include/transform.py", line 13, in transform_data
    timestamp = response['timestamp']
KeyError: 'timestamp'
[2024-04-12T22:52:01.538+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=KingFX1_ETL, task_id=Transform_response, execution_date=20240411T000000, start_date=20240412T225201, end_date=20240412T225201
[2024-04-12T22:52:01.549+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 74 for task Transform_response ('timestamp'; 3060)
[2024-04-12T22:52:01.573+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-12T23:32:59.547+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: KingFX1_ETL.Transform_response scheduled__2024-04-11T00:00:00+00:00 [queued]>
[2024-04-12T23:32:59.691+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: KingFX1_ETL.Transform_response scheduled__2024-04-11T00:00:00+00:00 [queued]>
[2024-04-12T23:32:59.692+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-12T23:32:59.711+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): Transform_response> on 2024-04-11 00:00:00+00:00
[2024-04-12T23:32:59.716+0000] {standard_task_runner.py:60} INFO - Started process 3678 to run task
[2024-04-12T23:32:59.720+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'KingFX1_ETL', 'Transform_response', 'scheduled__2024-04-11T00:00:00+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/include/fx_dag.py', '--cfg-path', '/tmp/tmp8vhv6nkr']
[2024-04-12T23:32:59.723+0000] {standard_task_runner.py:88} INFO - Job 77: Subtask Transform_response
[2024-04-12T23:32:59.783+0000] {task_command.py:423} INFO - Running <TaskInstance: KingFX1_ETL.Transform_response scheduled__2024-04-11T00:00:00+00:00 [running]> on host 65f2ce3f86e2
[2024-04-12T23:32:59.871+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='KingFX1_ETL' AIRFLOW_CTX_TASK_ID='Transform_response' AIRFLOW_CTX_EXECUTION_DATE='2024-04-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-11T00:00:00+00:00'
[2024-04-12T23:32:59.873+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/include/transform.py", line 13, in transform_data
    timestamp = response['timestamp']
KeyError: 'timestamp'
[2024-04-12T23:32:59.889+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=KingFX1_ETL, task_id=Transform_response, execution_date=20240411T000000, start_date=20240412T233259, end_date=20240412T233259
[2024-04-12T23:32:59.903+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 77 for task Transform_response ('timestamp'; 3678)
[2024-04-12T23:32:59.933+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
